const GROWTH_MIGRATION_ID='20260917_017_growth_channels';
async function runGrowthMigration(sequelize){await sequelize.query(`CREATE TABLE IF NOT EXISTS schema_migrations (id VARCHAR(160) PRIMARY KEY,"appliedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);const[rows]=await sequelize.query('SELECT id FROM schema_migrations WHERE id=:id',{replacements:{id:GROWTH_MIGRATION_ID}});if(rows.length)return;const transaction=await sequelize.transaction();try{const statements=[
`CREATE TABLE IF NOT EXISTS customers (id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name VARCHAR(160),phone VARCHAR(40) NOT NULL,email VARCHAR(320),"consentMarketing" BOOLEAN NOT NULL DEFAULT FALSE,"loyaltyPoints" BIGINT NOT NULL DEFAULT 0,"walletMinor" BIGINT NOT NULL DEFAULT 0,"visitCount" INTEGER NOT NULL DEFAULT 0,"totalSpendMinor" BIGINT NOT NULL DEFAULT 0,"lastVisitAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE UNIQUE INDEX IF NOT EXISTS customer_tenant_phone_unique ON customers ("tenantId",phone)`,
`CREATE TABLE IF NOT EXISTS guest_order_requests (id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"tableId" UUID NULL REFERENCES restaurant_tables(id) ON DELETE SET NULL,"customerId" UUID NULL REFERENCES customers(id) ON DELETE SET NULL,channel VARCHAR(32) NOT NULL,fulfillment VARCHAR(32) NOT NULL,"guestName" VARCHAR(160),phone VARCHAR(40),cart JSONB NOT NULL,"subtotalMinor" BIGINT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'PENDING',notes TEXT,"idempotencyKey" VARCHAR(180),"acceptedOrderId" UUID NULL REFERENCES orders(id) ON DELETE SET NULL,"acceptedByUserId" UUID NULL REFERENCES users(id) ON DELETE SET NULL,"acceptedAt" TIMESTAMPTZ,"rejectionReason" TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE UNIQUE INDEX IF NOT EXISTS guest_order_idempotency_unique ON guest_order_requests ("tenantId","idempotencyKey") WHERE "idempotencyKey" IS NOT NULL`,
`CREATE INDEX IF NOT EXISTS guest_order_queue_idx ON guest_order_requests ("tenantId","branchId",status,"createdAt")`,
`CREATE TABLE IF NOT EXISTS customer_feedback (id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"customerId" UUID NULL REFERENCES customers(id) ON DELETE SET NULL,"orderId" UUID NULL REFERENCES orders(id) ON DELETE SET NULL,rating INTEGER NOT NULL,comment TEXT,"contactAllowed" BOOLEAN NOT NULL DEFAULT FALSE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE IF NOT EXISTS offers (id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,code VARCHAR(40) NOT NULL,name VARCHAR(160) NOT NULL,"discountType" VARCHAR(24) NOT NULL,"discountValue" BIGINT NOT NULL,"minimumSpendMinor" BIGINT NOT NULL DEFAULT 0,"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,active BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE UNIQUE INDEX IF NOT EXISTS offer_tenant_code_unique ON offers ("tenantId",code)`,
`CREATE TABLE IF NOT EXISTS loyalty_transactions (id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"customerId" UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,"orderId" UUID NULL REFERENCES orders(id) ON DELETE SET NULL,"pointsDelta" BIGINT NOT NULL,"walletDeltaMinor" BIGINT NOT NULL DEFAULT 0,reason TEXT NOT NULL,"actorUserId" UUID NULL REFERENCES users(id) ON DELETE SET NULL,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`
];for(const statement of statements)await sequelize.query(statement,{transaction});await sequelize.query('INSERT INTO schema_migrations (id,"appliedAt") VALUES (:id,NOW())',{replacements:{id:GROWTH_MIGRATION_ID},transaction});await transaction.commit();console.log(`[database] applied migration ${GROWTH_MIGRATION_ID}`);}catch(error){await transaction.rollback();throw error;}}
module.exports={runGrowthMigration,GROWTH_MIGRATION_ID};
