const OPERATIONS_MIGRATION_ID='20260917_019_operations';
async function runOperationsMigration(sequelize){await sequelize.query(`CREATE TABLE IF NOT EXISTS schema_migrations(id VARCHAR(160) PRIMARY KEY,"appliedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`);const[rows]=await sequelize.query('SELECT id FROM schema_migrations WHERE id=:id',{replacements:{id:OPERATIONS_MIGRATION_ID}});if(rows.length)return;const t=await sequelize.transaction();try{const statements=[
`CREATE TABLE procurement_documents(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"documentType" VARCHAR(32) NOT NULL,"documentNumber" VARCHAR(80) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',"vendorId" UUID NULL REFERENCES suppliers(id) ON DELETE SET NULL,"parentId" UUID NULL REFERENCES procurement_documents(id) ON DELETE SET NULL,"amountMinor" BIGINT NOT NULL DEFAULT 0,payload JSONB NOT NULL DEFAULT '{}'::jsonb,attachment JSONB, "ocrResult" JSONB,"createdByUserId" UUID NOT NULL REFERENCES users(id),"approvedByUserId" UUID NULL REFERENCES users(id),"approvedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE("tenantId","documentNumber"))`,
`CREATE TABLE vendor_metrics(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"vendorId" UUID NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE,"productId" UUID NULL REFERENCES products(id) ON DELETE SET NULL,"quotedPriceMinor" BIGINT,"onTimeRateBps" INTEGER NOT NULL DEFAULT 10000,"qualityScore" INTEGER NOT NULL DEFAULT 100,"leadTimeDays" INTEGER NOT NULL DEFAULT 0,notes TEXT,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE ops_tasks(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,title VARCHAR(240) NOT NULL,description TEXT,status VARCHAR(24) NOT NULL DEFAULT 'OPEN',priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL',recurrence VARCHAR(80),"dueAt" TIMESTAMPTZ,"assigneeUserId" UUID NULL REFERENCES users(id),evidence JSONB,score INTEGER,"createdByUserId" UUID NOT NULL REFERENCES users(id),"approvedByUserId" UUID NULL REFERENCES users(id),"completedAt" TIMESTAMPTZ,"escalatedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE employee_records(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"userId" UUID NULL REFERENCES users(id),"employeeCode" VARCHAR(60) NOT NULL,name VARCHAR(180) NOT NULL,phone VARCHAR(40),"jobTitle" VARCHAR(120) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',"payRateMinor" BIGINT NOT NULL DEFAULT 0,"joinedOn" DATE,documents JSONB NOT NULL DEFAULT '[]'::jsonb,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE("tenantId","employeeCode"))`,
`CREATE TABLE workforce_events(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NOT NULL REFERENCES branches(id) ON DELETE CASCADE,"employeeId" UUID NOT NULL REFERENCES employee_records(id) ON DELETE CASCADE,"eventType" VARCHAR(32) NOT NULL,"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,status VARCHAR(24) NOT NULL DEFAULT 'PENDING',"amountMinor" BIGINT NOT NULL DEFAULT 0,payload JSONB NOT NULL DEFAULT '{}'::jsonb,"createdByUserId" UUID NOT NULL REFERENCES users(id),"approvedByUserId" UUID NULL REFERENCES users(id),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE central_templates(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,"templateType" VARCHAR(32) NOT NULL,version INTEGER NOT NULL DEFAULT 1,status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',payload JSONB NOT NULL DEFAULT '{}'::jsonb,"createdByUserId" UUID NOT NULL REFERENCES users(id),"publishedAt" TIMESTAMPTZ,"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE central_dispatches(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"sourceBranchId" UUID NOT NULL REFERENCES branches(id),"destinationBranchId" UUID NOT NULL REFERENCES branches(id),"templateId" UUID NULL REFERENCES central_templates(id),status VARCHAR(24) NOT NULL DEFAULT 'DISPATCHED',payload JSONB NOT NULL DEFAULT '{}'::jsonb,"dispatchedAt" TIMESTAMPTZ NOT NULL,"receivedAt" TIMESTAMPTZ,"createdByUserId" UUID NOT NULL REFERENCES users(id),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
`CREATE TABLE insight_automations(id UUID PRIMARY KEY,"tenantId" UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,"branchId" UUID NULL REFERENCES branches(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,"reportType" VARCHAR(60) NOT NULL,schedule VARCHAR(80),"alertRules" JSONB NOT NULL DEFAULT '{}'::jsonb,status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',"lastRunAt" TIMESTAMPTZ,"lastResult" JSONB,"createdByUserId" UUID NOT NULL REFERENCES users(id),"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`];for(const statement of statements)await sequelize.query(statement,{transaction:t});await sequelize.query('INSERT INTO schema_migrations(id,"appliedAt")VALUES(:id,NOW())',{replacements:{id:OPERATIONS_MIGRATION_ID},transaction:t});await t.commit();}catch(error){await t.rollback();throw error;}}
module.exports={OPERATIONS_MIGRATION_ID,runOperationsMigration};
