import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'managementSystemLocale';

export const LANGUAGES = [
  { id: 'en', short: 'EN', name: 'English' },
  { id: 'hi', short: 'हि', name: 'हिन्दी' },
  { id: 'mr', short: 'म', name: 'मराठी' }
];

const en = {
  'common.refresh':'Refresh','common.search':'Search','common.create':'Create','common.add':'Add','common.cancel':'Cancel','common.save':'Save','common.close':'Close','common.download':'Download','common.status':'Status','common.active':'Active','common.pending':'Pending','common.allBranches':'All branches','common.branch':'Branch','common.business':'Business','common.date':'Date','common.from':'From','common.to':'To','common.language':'Language','common.format':'Format','common.role':'Role','common.email':'Email','common.amount':'Amount','common.loading':'Loading…','common.noData':'No data available','common.signOut':'Sign out',
  'nav.platform':'Platform','nav.operations':'Operations','nav.overview':'Overview','nav.tenants':'Tenants','nav.branches':'Branches','nav.inventory':'Inventory','nav.sales':'Sales & Orders','nav.restaurant':'Restaurant','nav.analytics':'Analytics','nav.reports':'Reports','nav.staff':'Staff',
  'auth.top':'Outlet Management Platform · Multi-outlet operations','auth.securityTop':'Role-based access · Live server permission checks','auth.kicker':'Inventory · sales · restaurants · staff','auth.copy':'One workspace for multi-outlet inventory, bar and restaurant operations, wine-shop sales, staff accountability and management reporting.','auth.point1':'ML-based alcohol inventory and bottle-level control','auth.point2':'Tenant, branch and staff permissions checked live','auth.point3':'Restaurant, wine-shop and reporting workflows in one console','auth.secureTitle':'Secure by design','auth.secureBody':'Google verifies identity first. The backend then resolves the current tenant, branch and role before protected data is returned.','auth.platformAccess':'Platform access','auth.signIn':'Sign in to Outlet OS','auth.signInCopy':'Continue with the Google account assigned by your platform or tenant administrator.','auth.google':'Google sign in','auth.managed':'Managed access','auth.googleAccount':'Google account','auth.pendingHint':'New identities are captured as pending until an administrator assigns platform, tenant or branch access.','auth.accessModel':'access model','auth.superAdmin':'Super Admin','auth.superAdminCopy':'Creates tenants and platform access.','auth.tenantAdmin':'Tenant Admin','auth.tenantAdminCopy':'Creates outlets and assigns staff.','auth.branchStaff':'Branch Staff','auth.branchStaffCopy':'Works only inside assigned outlets.','auth.identityVerified':'Identity verified','auth.waiting':'Waiting for access assignment','auth.waitingCopy':'Your account is verified, but it does not yet have an active tenant or branch role.','auth.waitingCopy2':'Once an administrator assigns access, the same Google login will open the authorised workspace automatically.','auth.refreshAccess':'Refresh access',
  'overview.eyebrow':'Operate · control · reconcile · report','overview.online':'Operations online','overview.titleA':'Operations','overview.titleB':'Workbench','overview.copy':'Manage outlets, staff, inventory, sales, restaurant service, analytics and multilingual reports from one branch-aware operating view.','overview.readiness':'Operations readiness','overview.phase':'Phase 7','overview.phaseCopy':'Core operations and multilingual reports are connected. The interface can now switch between English, Hindi and Marathi while keeping the same role-based workflows.','overview.quick':'Quick access','overview.workspace':'Workspace','overview.assignedBranches':'Assigned branches','overview.liveAccess':'Live access','overview.inventoryBase':'Inventory base','overview.currentRole':'Current role',
  'tenant.management':'Tenant management','tenant.platformAdmin':'Platform administration','tenant.create':'Create tenant','tenant.groupName':'Business / group name','tenant.firstAdmin':'First Tenant Admin email','tenant.noTenants':'No tenants yet','tenant.noTenantsCopy':'Create the first business group to begin outlet setup.','branch.management':'Branch management','branch.add':'Add outlet','branch.name':'Branch name','branch.code':'Branch code','branch.type':'Outlet type','branch.bar':'Bar + Restaurant','branch.wineShop':'Wine Shop','branch.noBranches':'No outlets configured','branch.noBranchesCopy':'Create the first branch to begin inventory and staff setup.',
  'inventory.title':'Inventory','inventory.subtitle':'Products, stock, purchases and movement control','inventory.stock':'Stock','inventory.products':'Products','inventory.purchases':'Purchases','inventory.adjustments':'Adjustments','inventory.suppliers':'Suppliers','inventory.history':'History','inventory.ml':'ML stock','inventory.bottle':'Bottle','inventory.pour':'Pour',
  'sales.title':'Sales & Orders','sales.subtitle':'Counter and wine-shop POS','sales.cart':'Current cart','sales.checkout':'Checkout','sales.payment':'Payment method','sales.cash':'Cash','sales.card':'Card','sales.upi':'UPI','sales.other':'Other','sales.recent':'Recent sales','sales.emptyCart':'Cart is empty',
  'restaurant.title':'Restaurant Operations','restaurant.subtitle':'Tables · waiter orders · QR menu · settlement','restaurant.service':'Service','restaurant.tables':'Tables & QR','restaurant.publicMenu':'Public Menu','restaurant.newOrder':'New table order','restaurant.activeOrders':'Active & unresolved orders','restaurant.openOrder':'Open order','restaurant.markServed':'Mark served','restaurant.requestPayment':'Request payment','restaurant.pay':'Mark paid','restaurant.cancelOrder':'Cancel order','restaurant.createTable':'Create table','restaurant.publishMenu':'Publish menu item','restaurant.waiter':'Waiter',
  'staff.title':'Staff & Access','staff.subtitle':'Assign named staff to each outlet. Invited users activate automatically when they first sign in with the matching Google email.','staff.assign':'Assign staff','staff.googleEmail':'Google account email','staff.branchRole':'Branch role','staff.assigned':'Assigned staff','staff.suspend':'Suspend','staff.restore':'Restore','staff.noStaff':'No staff assignments',
  'analytics.title':'Analytics & P&L','analytics.subtitle':'Consolidated operating visibility built directly from paid orders, inventory movements, payments and posted branch expenses.','analytics.todaySales':'Today sales','analytics.mtdSales':'MTD sales','analytics.rangeSales':'Range sales','analytics.grossProfit':'Gross profit','analytics.operating':'Operating P&L','analytics.inventoryValue':'Inventory value','analytics.unresolved':'Unresolved tables','analytics.branchComparison':'Branch comparison','analytics.paymentMix':'Payment mix','analytics.dailyRevenue':'Daily revenue','analytics.bottlePour':'Bottle vs pour','analytics.topProducts':'Top products','analytics.lowStock':'Low stock','analytics.waiterPerformance':'Waiter performance','analytics.expenseMix':'Expense mix','analytics.postExpense':'Post branch expense','analytics.applyRange':'Apply range',
  'reports.title':'Reports','reports.subtitle':'Generate detailed operational reports directly from source-of-truth sales, inventory, restaurant and finance records.','reports.builder':'Report builder','reports.generate':'Generate report','reports.catalogue':'Report catalogue','reports.history':'Report history','reports.scope':'Scope','reports.allScope':'All branches / consolidated','reports.report':'Report','reports.stored':'Stored securely','reports.noHistory':'No reports generated yet','reports.noHistoryCopy':'Generated files will appear here and remain available through authenticated download.','reports.generating':'Generating…','reports.refreshHistory':'Refresh history',
  'publicMenu.menu':'Menu','publicMenu.table':'Your table','publicMenu.search':'Search food, drinks or brands…','publicMenu.all':'All','publicMenu.featured':'Featured','publicMenu.noItems':'No menu items found','publicMenu.noItemsCopy':'Try another section or search term.','publicMenu.unavailable':'Menu unavailable','publicMenu.loading':'Loading menu…','publicMenu.subtitle':'Browse the menu and prices for this outlet. Order with your waiter when ready.'
};

const hi = {
  'common.refresh':'रीफ्रेश','common.search':'खोजें','common.create':'बनाएँ','common.add':'जोड़ें','common.cancel':'रद्द करें','common.save':'सेव करें','common.close':'बंद करें','common.download':'डाउनलोड','common.status':'स्थिति','common.active':'सक्रिय','common.pending':'लंबित','common.allBranches':'सभी शाखाएँ','common.branch':'शाखा','common.business':'व्यवसाय','common.date':'तारीख','common.from':'से','common.to':'तक','common.language':'भाषा','common.format':'फ़ॉर्मेट','common.role':'भूमिका','common.email':'ईमेल','common.amount':'राशि','common.loading':'लोड हो रहा है…','common.noData':'डेटा उपलब्ध नहीं','common.signOut':'साइन आउट',
  'nav.platform':'प्लेटफ़ॉर्म','nav.operations':'ऑपरेशन्स','nav.overview':'ओवरव्यू','nav.tenants':'टेनेंट','nav.branches':'शाखाएँ','nav.inventory':'इन्वेंटरी','nav.sales':'बिक्री और ऑर्डर','nav.restaurant':'रेस्टोरेंट','nav.analytics':'एनालिटिक्स','nav.reports':'रिपोर्ट्स','nav.staff':'स्टाफ',
  'auth.top':'आउटलेट मैनेजमेंट प्लेटफ़ॉर्म · मल्टी-आउटलेट ऑपरेशन्स','auth.securityTop':'भूमिका आधारित एक्सेस · लाइव सर्वर अनुमति जाँच','auth.kicker':'इन्वेंटरी · बिक्री · रेस्टोरेंट · स्टाफ','auth.copy':'मल्टी-आउटलेट इन्वेंटरी, बार व रेस्टोरेंट ऑपरेशन्स, वाइन-शॉप बिक्री, स्टाफ जवाबदेही और मैनेजमेंट रिपोर्टिंग के लिए एक वर्कस्पेस।','auth.point1':'ML आधारित अल्कोहल इन्वेंटरी और बोतल नियंत्रण','auth.point2':'टेनेंट, शाखा और स्टाफ अनुमतियों की लाइव जाँच','auth.point3':'रेस्टोरेंट, वाइन-शॉप और रिपोर्टिंग एक कंसोल में','auth.secureTitle':'सुरक्षित डिज़ाइन','auth.secureBody':'Google पहले पहचान सत्यापित करता है। फिर बैकएंड मौजूदा टेनेंट, शाखा और भूमिका जाँचता है।','auth.platformAccess':'प्लेटफ़ॉर्म एक्सेस','auth.signIn':'Outlet OS में साइन इन करें','auth.signInCopy':'अपने प्लेटफ़ॉर्म या टेनेंट एडमिन द्वारा असाइन Google खाते से जारी रखें।','auth.google':'Google साइन इन','auth.managed':'मैनेज्ड एक्सेस','auth.googleAccount':'Google खाता','auth.pendingHint':'नई पहचान एडमिन द्वारा एक्सेस असाइन होने तक लंबित रहती है।','auth.accessModel':'एक्सेस मॉडल','auth.superAdmin':'सुपर एडमिन','auth.superAdminCopy':'टेनेंट और प्लेटफ़ॉर्म एक्सेस बनाता है।','auth.tenantAdmin':'टेनेंट एडमिन','auth.tenantAdminCopy':'आउटलेट बनाता और स्टाफ असाइन करता है।','auth.branchStaff':'ब्रांच स्टाफ','auth.branchStaffCopy':'केवल असाइन आउटलेट में काम करता है।','auth.identityVerified':'पहचान सत्यापित','auth.waiting':'एक्सेस असाइनमेंट की प्रतीक्षा','auth.waitingCopy':'आपका खाता सत्यापित है, लेकिन अभी सक्रिय टेनेंट या शाखा भूमिका नहीं है।','auth.waitingCopy2':'एडमिन द्वारा एक्सेस असाइन होने पर यही Google लॉगिन वर्कस्पेस खोल देगा।','auth.refreshAccess':'एक्सेस रीफ्रेश करें',
  'overview.eyebrow':'ऑपरेट · कंट्रोल · मिलान · रिपोर्ट','overview.online':'ऑपरेशन्स ऑनलाइन','overview.titleA':'ऑपरेशन्स','overview.titleB':'वर्कबेंच','overview.copy':'आउटलेट, स्टाफ, इन्वेंटरी, बिक्री, रेस्टोरेंट सेवा, एनालिटिक्स और बहुभाषी रिपोर्ट एक ही दृश्य से प्रबंधित करें।','overview.readiness':'ऑपरेशन्स तैयारी','overview.phase':'चरण 7','overview.phaseCopy':'मुख्य ऑपरेशन्स और बहुभाषी रिपोर्ट जुड़े हैं। इंटरफ़ेस अब अंग्रेज़ी, हिन्दी और मराठी में स्विच किया जा सकता है।','overview.quick':'क्विक एक्सेस','overview.workspace':'वर्कस्पेस','overview.assignedBranches':'असाइन शाखाएँ','overview.liveAccess':'लाइव एक्सेस','overview.inventoryBase':'इन्वेंटरी बेस','overview.currentRole':'वर्तमान भूमिका',
  'tenant.management':'टेनेंट प्रबंधन','tenant.platformAdmin':'प्लेटफ़ॉर्म प्रशासन','tenant.create':'टेनेंट बनाएँ','tenant.groupName':'व्यवसाय / समूह नाम','tenant.firstAdmin':'पहला टेनेंट एडमिन ईमेल','tenant.noTenants':'अभी कोई टेनेंट नहीं','tenant.noTenantsCopy':'आउटलेट सेटअप शुरू करने के लिए पहला व्यवसाय समूह बनाएँ।','branch.management':'शाखा प्रबंधन','branch.add':'आउटलेट जोड़ें','branch.name':'शाखा नाम','branch.code':'शाखा कोड','branch.type':'आउटलेट प्रकार','branch.bar':'बार + रेस्टोरेंट','branch.wineShop':'वाइन शॉप','branch.noBranches':'कोई आउटलेट कॉन्फ़िगर नहीं','branch.noBranchesCopy':'इन्वेंटरी और स्टाफ सेटअप के लिए पहली शाखा बनाएँ।',
  'inventory.title':'इन्वेंटरी','inventory.subtitle':'उत्पाद, स्टॉक, खरीद और मूवमेंट नियंत्रण','inventory.stock':'स्टॉक','inventory.products':'उत्पाद','inventory.purchases':'खरीद','inventory.adjustments':'एडजस्टमेंट','inventory.suppliers':'आपूर्तिकर्ता','inventory.history':'इतिहास','inventory.ml':'ML स्टॉक','inventory.bottle':'बोतल','inventory.pour':'पोरेशन',
  'sales.title':'बिक्री और ऑर्डर','sales.subtitle':'काउंटर और वाइन-शॉप POS','sales.cart':'वर्तमान कार्ट','sales.checkout':'चेकआउट','sales.payment':'भुगतान माध्यम','sales.cash':'नकद','sales.card':'कार्ड','sales.upi':'UPI','sales.other':'अन्य','sales.recent':'हाल की बिक्री','sales.emptyCart':'कार्ट खाली है',
  'restaurant.title':'रेस्टोरेंट ऑपरेशन्स','restaurant.subtitle':'टेबल · वेटर ऑर्डर · QR मेनू · सेटलमेंट','restaurant.service':'सर्विस','restaurant.tables':'टेबल और QR','restaurant.publicMenu':'पब्लिक मेनू','restaurant.newOrder':'नया टेबल ऑर्डर','restaurant.activeOrders':'सक्रिय और अनसुलझे ऑर्डर','restaurant.openOrder':'ऑर्डर खोलें','restaurant.markServed':'सर्व्ड मार्क करें','restaurant.requestPayment':'भुगतान माँगें','restaurant.pay':'पेड मार्क करें','restaurant.cancelOrder':'ऑर्डर रद्द करें','restaurant.createTable':'टेबल बनाएँ','restaurant.publishMenu':'मेनू आइटम प्रकाशित करें','restaurant.waiter':'वेटर',
  'staff.title':'स्टाफ और एक्सेस','staff.subtitle':'हर आउटलेट में नामित स्टाफ असाइन करें। मेल खाते Google ईमेल से पहली बार साइन इन करने पर आमंत्रण सक्रिय हो जाता है।','staff.assign':'स्टाफ असाइन करें','staff.googleEmail':'Google खाता ईमेल','staff.branchRole':'शाखा भूमिका','staff.assigned':'असाइन स्टाफ','staff.suspend':'निलंबित करें','staff.restore':'बहाल करें','staff.noStaff':'कोई स्टाफ असाइनमेंट नहीं',
  'analytics.title':'एनालिटिक्स और P&L','analytics.subtitle':'पेड ऑर्डर, इन्वेंटरी मूवमेंट, भुगतान और शाखा खर्च से सीधे समेकित ऑपरेशनल दृश्य।','analytics.todaySales':'आज की बिक्री','analytics.mtdSales':'माह की बिक्री','analytics.rangeSales':'अवधि बिक्री','analytics.grossProfit':'सकल लाभ','analytics.operating':'परिचालन P&L','analytics.inventoryValue':'इन्वेंटरी मूल्य','analytics.unresolved':'अनसुलझे टेबल','analytics.branchComparison':'शाखा तुलना','analytics.paymentMix':'भुगतान मिश्रण','analytics.dailyRevenue':'दैनिक राजस्व','analytics.bottlePour':'बोतल बनाम पोरेशन','analytics.topProducts':'शीर्ष उत्पाद','analytics.lowStock':'कम स्टॉक','analytics.waiterPerformance':'वेटर प्रदर्शन','analytics.expenseMix':'खर्च मिश्रण','analytics.postExpense':'शाखा खर्च दर्ज करें','analytics.applyRange':'अवधि लागू करें',
  'reports.title':'रिपोर्ट्स','reports.subtitle':'बिक्री, इन्वेंटरी, रेस्टोरेंट और वित्तीय रिकॉर्ड से विस्तृत ऑपरेशनल रिपोर्ट बनाएँ।','reports.builder':'रिपोर्ट बिल्डर','reports.generate':'रिपोर्ट बनाएँ','reports.catalogue':'रिपोर्ट कैटलॉग','reports.history':'रिपोर्ट इतिहास','reports.scope':'दायरा','reports.allScope':'सभी शाखाएँ / समेकित','reports.report':'रिपोर्ट','reports.stored':'सुरक्षित रूप से संग्रहित','reports.noHistory':'अभी कोई रिपोर्ट नहीं','reports.noHistoryCopy':'तैयार रिपोर्ट यहाँ दिखाई देंगी और सुरक्षित डाउनलोड के लिए उपलब्ध रहेंगी।','reports.generating':'रिपोर्ट बन रही है…','reports.refreshHistory':'इतिहास रीफ्रेश करें',
  'publicMenu.menu':'मेनू','publicMenu.table':'आपकी टेबल','publicMenu.search':'खाना, पेय या ब्रांड खोजें…','publicMenu.all':'सभी','publicMenu.featured':'विशेष','publicMenu.noItems':'कोई मेनू आइटम नहीं मिला','publicMenu.noItemsCopy':'दूसरा सेक्शन या खोज शब्द आज़माएँ।','publicMenu.unavailable':'मेनू उपलब्ध नहीं','publicMenu.loading':'मेनू लोड हो रहा है…','publicMenu.subtitle':'इस आउटलेट का मेनू और कीमतें देखें। तैयार होने पर वेटर से ऑर्डर करें।'
};

const mr = {
  'common.refresh':'रिफ्रेश','common.search':'शोधा','common.create':'तयार करा','common.add':'जोडा','common.cancel':'रद्द करा','common.save':'सेव्ह करा','common.close':'बंद करा','common.download':'डाउनलोड','common.status':'स्थिती','common.active':'सक्रिय','common.pending':'प्रलंबित','common.allBranches':'सर्व शाखा','common.branch':'शाखा','common.business':'व्यवसाय','common.date':'तारीख','common.from':'पासून','common.to':'पर्यंत','common.language':'भाषा','common.format':'फॉरमॅट','common.role':'भूमिका','common.email':'ईमेल','common.amount':'रक्कम','common.loading':'लोड होत आहे…','common.noData':'डेटा उपलब्ध नाही','common.signOut':'साइन आउट',
  'nav.platform':'प्लॅटफॉर्म','nav.operations':'ऑपरेशन्स','nav.overview':'ओव्हरव्ह्यू','nav.tenants':'टेनंट','nav.branches':'शाखा','nav.inventory':'इन्व्हेंटरी','nav.sales':'विक्री आणि ऑर्डर्स','nav.restaurant':'रेस्टॉरंट','nav.analytics':'अॅनालिटिक्स','nav.reports':'अहवाल','nav.staff':'स्टाफ',
  'auth.top':'आउटलेट मॅनेजमेंट प्लॅटफॉर्म · मल्टी-आउटलेट ऑपरेशन्स','auth.securityTop':'भूमिकेनुसार प्रवेश · लाईव्ह सर्व्हर परवानगी तपासणी','auth.kicker':'इन्व्हेंटरी · विक्री · रेस्टॉरंट · स्टाफ','auth.copy':'मल्टी-आउटलेट इन्व्हेंटरी, बार व रेस्टॉरंट ऑपरेशन्स, वाइन-शॉप विक्री, स्टाफ जबाबदारी आणि व्यवस्थापन अहवालांसाठी एक वर्कस्पेस.','auth.point1':'ML आधारित अल्कोहोल इन्व्हेंटरी आणि बाटली नियंत्रण','auth.point2':'टेनंट, शाखा आणि स्टाफ परवानग्यांची लाईव्ह तपासणी','auth.point3':'रेस्टॉरंट, वाइन-शॉप आणि अहवाल एकाच कन्सोलमध्ये','auth.secureTitle':'सुरक्षित रचना','auth.secureBody':'Google प्रथम ओळख सत्यापित करते. त्यानंतर बॅकएंड सध्याचा टेनंट, शाखा आणि भूमिका तपासतो.','auth.platformAccess':'प्लॅटफॉर्म प्रवेश','auth.signIn':'Outlet OS मध्ये साइन इन करा','auth.signInCopy':'प्लॅटफॉर्म किंवा टेनंट अॅडमिनने दिलेल्या Google खात्याने पुढे जा.','auth.google':'Google साइन इन','auth.managed':'मॅनेज्ड प्रवेश','auth.googleAccount':'Google खाते','auth.pendingHint':'अॅडमिन प्रवेश देईपर्यंत नवीन ओळख प्रलंबित राहते.','auth.accessModel':'प्रवेश मॉडेल','auth.superAdmin':'सुपर अॅडमिन','auth.superAdminCopy':'टेनंट आणि प्लॅटफॉर्म प्रवेश तयार करतो.','auth.tenantAdmin':'टेनंट अॅडमिन','auth.tenantAdminCopy':'आउटलेट तयार करतो आणि स्टाफ नियुक्त करतो.','auth.branchStaff':'ब्रांच स्टाफ','auth.branchStaffCopy':'फक्त नियुक्त आउटलेटमध्ये काम करतो.','auth.identityVerified':'ओळख सत्यापित','auth.waiting':'प्रवेश नियुक्तीची प्रतीक्षा','auth.waitingCopy':'तुमचे खाते सत्यापित आहे, पण सक्रिय टेनंट किंवा शाखा भूमिका अजून नाही.','auth.waitingCopy2':'अॅडमिन प्रवेश दिल्यानंतर हाच Google लॉगिन अधिकृत वर्कस्पेस उघडेल.','auth.refreshAccess':'प्रवेश रिफ्रेश करा',
  'overview.eyebrow':'ऑपरेट · कंट्रोल · ताळमेळ · रिपोर्ट','overview.online':'ऑपरेशन्स ऑनलाइन','overview.titleA':'ऑपरेशन्स','overview.titleB':'वर्कबेंच','overview.copy':'आउटलेट, स्टाफ, इन्व्हेंटरी, विक्री, रेस्टॉरंट सेवा, अॅनालिटिक्स आणि बहुभाषिक अहवाल एका दृश्यातून व्यवस्थापित करा.','overview.readiness':'ऑपरेशन्स तयारी','overview.phase':'टप्पा 7','overview.phaseCopy':'मुख्य ऑपरेशन्स आणि बहुभाषिक अहवाल जोडले आहेत. इंटरफेस आता इंग्रजी, हिंदी आणि मराठीमध्ये बदलता येतो.','overview.quick':'क्विक प्रवेश','overview.workspace':'वर्कस्पेस','overview.assignedBranches':'नियुक्त शाखा','overview.liveAccess':'लाईव्ह प्रवेश','overview.inventoryBase':'इन्व्हेंटरी बेस','overview.currentRole':'सध्याची भूमिका',
  'tenant.management':'टेनंट व्यवस्थापन','tenant.platformAdmin':'प्लॅटफॉर्म प्रशासन','tenant.create':'टेनंट तयार करा','tenant.groupName':'व्यवसाय / समूह नाव','tenant.firstAdmin':'पहिला टेनंट अॅडमिन ईमेल','tenant.noTenants':'अजून टेनंट नाही','tenant.noTenantsCopy':'आउटलेट सेटअप सुरू करण्यासाठी पहिला व्यवसाय समूह तयार करा.','branch.management':'शाखा व्यवस्थापन','branch.add':'आउटलेट जोडा','branch.name':'शाखेचे नाव','branch.code':'शाखा कोड','branch.type':'आउटलेट प्रकार','branch.bar':'बार + रेस्टॉरंट','branch.wineShop':'वाइन शॉप','branch.noBranches':'आउटलेट कॉन्फिगर नाही','branch.noBranchesCopy':'इन्व्हेंटरी आणि स्टाफ सेटअपसाठी पहिली शाखा तयार करा.',
  'inventory.title':'इन्व्हेंटरी','inventory.subtitle':'उत्पादने, स्टॉक, खरेदी आणि मूव्हमेंट नियंत्रण','inventory.stock':'स्टॉक','inventory.products':'उत्पादने','inventory.purchases':'खरेदी','inventory.adjustments':'अॅडजस्टमेंट','inventory.suppliers':'पुरवठादार','inventory.history':'इतिहास','inventory.ml':'ML स्टॉक','inventory.bottle':'बाटली','inventory.pour':'पोर्शन',
  'sales.title':'विक्री आणि ऑर्डर्स','sales.subtitle':'काउंटर आणि वाइन-शॉप POS','sales.cart':'सध्याचे कार्ट','sales.checkout':'चेकआउट','sales.payment':'पेमेंट पद्धत','sales.cash':'रोख','sales.card':'कार्ड','sales.upi':'UPI','sales.other':'इतर','sales.recent':'अलीकडील विक्री','sales.emptyCart':'कार्ट रिकामे आहे',
  'restaurant.title':'रेस्टॉरंट ऑपरेशन्स','restaurant.subtitle':'टेबल · वेटर ऑर्डर्स · QR मेनू · सेटलमेंट','restaurant.service':'सेवा','restaurant.tables':'टेबल आणि QR','restaurant.publicMenu':'पब्लिक मेनू','restaurant.newOrder':'नवीन टेबल ऑर्डर','restaurant.activeOrders':'सक्रिय आणि प्रलंबित ऑर्डर्स','restaurant.openOrder':'ऑर्डर उघडा','restaurant.markServed':'सर्व्ह केले मार्क करा','restaurant.requestPayment':'पेमेंट मागवा','restaurant.pay':'पेड मार्क करा','restaurant.cancelOrder':'ऑर्डर रद्द करा','restaurant.createTable':'टेबल तयार करा','restaurant.publishMenu':'मेनू आयटम प्रकाशित करा','restaurant.waiter':'वेटर',
  'staff.title':'स्टाफ आणि प्रवेश','staff.subtitle':'प्रत्येक आउटलेटला नावासह स्टाफ नियुक्त करा. जुळणाऱ्या Google ईमेलने प्रथम साइन इन केल्यावर आमंत्रण सक्रिय होते.','staff.assign':'स्टाफ नियुक्त करा','staff.googleEmail':'Google खाते ईमेल','staff.branchRole':'शाखा भूमिका','staff.assigned':'नियुक्त स्टाफ','staff.suspend':'निलंबित करा','staff.restore':'पुन्हा सक्रिय करा','staff.noStaff':'स्टाफ नियुक्ती नाही',
  'analytics.title':'अॅनालिटिक्स आणि P&L','analytics.subtitle':'पेड ऑर्डर्स, इन्व्हेंटरी मूव्हमेंट, पेमेंट आणि शाखा खर्चातून थेट एकत्रित ऑपरेशनल दृश्य.','analytics.todaySales':'आजची विक्री','analytics.mtdSales':'महिन्याची विक्री','analytics.rangeSales':'कालावधी विक्री','analytics.grossProfit':'एकूण नफा','analytics.operating':'ऑपरेटिंग P&L','analytics.inventoryValue':'इन्व्हेंटरी मूल्य','analytics.unresolved':'प्रलंबित टेबल','analytics.branchComparison':'शाखा तुलना','analytics.paymentMix':'पेमेंट मिश्रण','analytics.dailyRevenue':'दैनिक महसूल','analytics.bottlePour':'बाटली विरुद्ध पोर्शन','analytics.topProducts':'टॉप उत्पादने','analytics.lowStock':'कमी स्टॉक','analytics.waiterPerformance':'वेटर कामगिरी','analytics.expenseMix':'खर्च मिश्रण','analytics.postExpense':'शाखा खर्च नोंदवा','analytics.applyRange':'कालावधी लागू करा',
  'reports.title':'अहवाल','reports.subtitle':'विक्री, इन्व्हेंटरी, रेस्टॉरंट आणि वित्तीय नोंदींमधून सविस्तर ऑपरेशनल अहवाल तयार करा.','reports.builder':'रिपोर्ट बिल्डर','reports.generate':'अहवाल तयार करा','reports.catalogue':'अहवाल कॅटलॉग','reports.history':'अहवाल इतिहास','reports.scope':'व्याप्ती','reports.allScope':'सर्व शाखा / एकत्रित','reports.report':'अहवाल','reports.stored':'सुरक्षितपणे संग्रहित','reports.noHistory':'अजून अहवाल नाही','reports.noHistoryCopy':'तयार अहवाल येथे दिसतील आणि सुरक्षित डाउनलोडसाठी उपलब्ध राहतील.','reports.generating':'अहवाल तयार होत आहे…','reports.refreshHistory':'इतिहास रिफ्रेश करा',
  'publicMenu.menu':'मेनू','publicMenu.table':'तुमचे टेबल','publicMenu.search':'खाद्यपदार्थ, पेय किंवा ब्रँड शोधा…','publicMenu.all':'सर्व','publicMenu.featured':'विशेष','publicMenu.noItems':'मेनू आयटम सापडले नाहीत','publicMenu.noItemsCopy':'दुसरा विभाग किंवा शोध शब्द वापरून पहा.','publicMenu.unavailable':'मेनू उपलब्ध नाही','publicMenu.loading':'मेनू लोड होत आहे…','publicMenu.subtitle':'या आउटलेटचा मेनू आणि किंमती पहा. तयार झाल्यावर वेटरकडे ऑर्डर द्या.'
};

const dictionaries = { en, hi: { ...en, ...hi }, mr: { ...en, ...mr } };

function initialLocale() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return dictionaries[stored] ? stored : 'en';
  } catch (_) { return 'en'; }
}

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState(initialLocale);
  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, locale); } catch (_) {}
    document.documentElement.lang = locale;
  }, [locale]);

  const value = useMemo(() => ({
    locale,
    setLocale: (next) => dictionaries[next] && setLocale(next),
    languages: LANGUAGES,
    t(key, vars = {}) {
      let text = dictionaries[locale]?.[key] || dictionaries.en[key] || key;
      for (const [name, value] of Object.entries(vars)) text = text.replaceAll(`{${name}}`, String(value));
      return text;
    }
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider');
  return value;
}

export function LanguageSwitcher({ compact = false }) {
  const { locale, setLocale, languages } = useLanguage();
  return (
    <div className={compact ? 'language-switcher compact' : 'language-switcher'} aria-label="Language">
      {languages.map((language) => (
        <button key={language.id} type="button" className={locale === language.id ? 'active' : ''} onClick={() => setLocale(language.id)} title={language.name}>
          {compact ? language.short : language.name}
        </button>
      ))}
    </div>
  );
}
