const express = require('express');
const { Device, PrintJob, AuditLog } = require('../models');
const { authenticate, requireApproved, requireBranchRoles } = require('../middleware/auth');

const router = express.Router();
const DEVICE_TYPES = ['RECEIPT_PRINTER','KOT_PRINTER','KDS','TERMINAL','CUSTOMER_DISPLAY','TOKEN_DISPLAY','CALLING_DEVICE','KIOSK'];
const CONNECTION_TYPES = ['BROWSER','USB','TCP','NETWORK','APP'];
router.use(authenticate,requireApproved);
function scope(req,res,next){return requireBranchRoles('BRANCH_MANAGER')(req,res,(error)=>{if(error)return next(error);if(String(req.branch.tenantId)!==String(req.params.tenantId))return res.status(404).json({message:'Branch not found in this business.'});next();});}
function clean(value,max=255){const text=String(value||'').trim();return text?text.slice(0,max):null;}
async function audit(req,action,entityType,entityId,metadata){await AuditLog.create({tenantId:req.params.tenantId,branchId:req.params.branchId,actorUserId:req.auditActorUserId||req.userId,action,entityType,entityId:String(entityId),metadata,ipAddress:req.ip||null});}

router.get('/tenants/:tenantId/branches/:branchId',scope,async(req,res,next)=>{try{const [devices,jobs]=await Promise.all([Device.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},order:[['name','ASC']]}),PrintJob.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},include:[{model:Device,as:'device',attributes:['id','name','deviceType']}],order:[['createdAt','DESC']],limit:30})]);res.json({devices,jobs});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId',scope,async(req,res,next)=>{try{const name=clean(req.body?.name,160);const deviceType=String(req.body?.deviceType||'').toUpperCase();const connectionType=String(req.body?.connectionType||'').toUpperCase();if(!name)return res.status(400).json({message:'Device name is required.'});if(!DEVICE_TYPES.includes(deviceType))return res.status(400).json({message:`deviceType must be one of: ${DEVICE_TYPES.join(', ')}`});if(!CONNECTION_TYPES.includes(connectionType))return res.status(400).json({message:`connectionType must be one of: ${CONNECTION_TYPES.join(', ')}`});const device=await Device.create({tenantId:req.params.tenantId,branchId:req.params.branchId,name,deviceType,connectionType,endpoint:clean(req.body?.endpoint,500),station:clean(req.body?.station,120),status:'ACTIVE',capabilities:req.body?.capabilities&&typeof req.body.capabilities==='object'?req.body.capabilities:{}});await audit(req,'DEVICE_REGISTERED','Device',device.id,{name,deviceType,connectionType,station:device.station});res.status(201).json({device});}catch(error){if(error?.name==='SequelizeUniqueConstraintError')return res.status(409).json({message:'A device with this name already exists in the branch.'});next(error);}});

router.patch('/tenants/:tenantId/branches/:branchId/:deviceId',scope,async(req,res,next)=>{try{const device=await Device.findOne({where:{id:req.params.deviceId,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!device)return res.status(404).json({message:'Device not found.'});if(req.body?.status!==undefined){const status=String(req.body.status).toUpperCase();if(!['ACTIVE','PAUSED','OFFLINE'].includes(status))return res.status(400).json({message:'Invalid device status.'});device.status=status;}if(req.body?.name!==undefined)device.name=clean(req.body.name,160)||device.name;if(req.body?.station!==undefined)device.station=clean(req.body.station,120);if(req.body?.endpoint!==undefined)device.endpoint=clean(req.body.endpoint,500);await device.save();await audit(req,'DEVICE_UPDATED','Device',device.id,{status:device.status,name:device.name,station:device.station});res.json({device});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/:deviceId/heartbeat',scope,async(req,res,next)=>{try{const device=await Device.findOne({where:{id:req.params.deviceId,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!device)return res.status(404).json({message:'Device not found.'});device.lastSeenAt=new Date();if(device.status==='OFFLINE')device.status='ACTIVE';if(req.body?.capabilities&&typeof req.body.capabilities==='object')device.capabilities={...device.capabilities,...req.body.capabilities};await device.save();res.json({device,health:'ONLINE'});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/:deviceId/test-print',scope,async(req,res,next)=>{try{const device=await Device.findOne({where:{id:req.params.deviceId,tenantId:req.params.tenantId,branchId:req.params.branchId,status:'ACTIVE'}});if(!device)return res.status(404).json({message:'Active device not found.'});const key=clean(req.body?.idempotencyKey,180);if(key){const existing=await PrintJob.findOne({where:{tenantId:req.params.tenantId,idempotencyKey:key}});if(existing)return res.json({job:existing,replayed:true});}const job=await PrintJob.create({tenantId:req.params.tenantId,branchId:req.params.branchId,deviceId:device.id,jobType:device.deviceType==='KOT_PRINTER'?'KOT_TEST':'RECEIPT_TEST',status:'PENDING',payload:{title:'OUTLET MANAGEMENT',lines:['Printer test',device.name,new Date().toISOString()]},idempotencyKey:key,createdByUserId:req.userId});await audit(req,'TEST_PRINT_QUEUED','PrintJob',job.id,{deviceId:device.id,deviceType:device.deviceType});res.status(201).json({job,replayed:false});}catch(error){next(error);}});

module.exports=router;
