const crypto = require('crypto');
const express = require('express');
const { AuditLog } = require('../models');
const { ApiKey, WebhookSubscription, WebhookDelivery } = require('../models/ecosystem');
const { authenticate, requireApproved, requireBranchRoles } = require('../middleware/auth');
const router = express.Router();
router.use(authenticate, requireApproved);
const hash = (value) => crypto.createHash('sha256').update(value).digest('hex');
const webhookSecret = (id) => crypto.createHmac('sha256', String(process.env.JWT_SECRET || 'local-development-secret')).update(`webhook:${id}`).digest('base64url');
function scope(req,res,next){return requireBranchRoles('BRANCH_MANAGER')(req,res,(error)=>{if(error)return next(error);if(!req.branch||String(req.branch.tenantId)!==String(req.params.tenantId))return res.status(404).json({message:'Branch not found in this business.'});next();});}
async function audit(req,action,type,id,metadata={}){await AuditLog.create({tenantId:req.params.tenantId,branchId:req.params.branchId,actorUserId:req.userId,action,entityType:type,entityId:String(id),metadata,ipAddress:req.ip||null});}
router.get('/tenants/:tenantId/branches/:branchId',scope,async(req,res,next)=>{try{const[keys,subscriptions,deliveries]=await Promise.all([ApiKey.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},attributes:{exclude:['keyHash']},order:[['createdAt','DESC']]}),WebhookSubscription.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},attributes:{exclude:['secretHash']},order:[['createdAt','DESC']]}),WebhookDelivery.findAll({where:{tenantId:req.params.tenantId},order:[['createdAt','DESC']],limit:100})]);res.json({keys,subscriptions,deliveries});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/keys',scope,async(req,res,next)=>{try{const name=String(req.body?.name||'').trim().slice(0,160);if(!name)return res.status(400).json({message:'Key name is required.'});const raw=`deva_${req.body?.sandbox===false?'live':'test'}_${crypto.randomBytes(24).toString('base64url')}`;const key=await ApiKey.create({tenantId:req.params.tenantId,branchId:req.params.branchId,name,keyPrefix:raw.slice(0,16),keyHash:hash(raw),scopes:Array.isArray(req.body?.scopes)?req.body.scopes:['catalogue:read','orders:write'],sandbox:req.body?.sandbox!==false,rateLimitPerMinute:Math.max(10,Math.min(600,Number(req.body?.rateLimitPerMinute||60))),expiresAt:req.body?.expiresAt||null,createdByUserId:req.userId});await audit(req,'API_KEY_CREATED','ApiKey',key.id,{name:key.name,scopes:key.scopes,sandbox:key.sandbox});res.status(201).json({key:{...key.toJSON(),keyHash:undefined},secret:raw,warning:'Copy this secret now. It will not be shown again.'});}catch(error){next(error);}});
router.delete('/tenants/:tenantId/branches/:branchId/keys/:id',scope,async(req,res,next)=>{try{const key=await ApiKey.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!key)return res.status(404).json({message:'API key not found.'});key.status='REVOKED';await key.save();await audit(req,'API_KEY_REVOKED','ApiKey',key.id);res.status(204).end();}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/webhooks',scope,async(req,res,next)=>{try{let url;try{url=new URL(req.body?.url);}catch(_){return res.status(400).json({message:'Valid webhook URL required.'});}if(url.protocol!=='https:'&&String(process.env.NODE_ENV).toLowerCase()==='production')return res.status(400).json({message:'Production webhook URLs must use HTTPS.'});if(/^(localhost|127\.|10\.|192\.168\.|169\.254\.|\[?::1\]?)/i.test(url.hostname))return res.status(400).json({message:'Private network webhook targets are not allowed.'});const id=crypto.randomUUID(),secret=webhookSecret(id);const subscription=await WebhookSubscription.create({id,tenantId:req.params.tenantId,branchId:req.params.branchId,url:url.toString(),events:Array.isArray(req.body?.events)?req.body.events:['order.created','order.paid'],secretHash:hash(secret),createdByUserId:req.userId});await audit(req,'WEBHOOK_SUBSCRIPTION_CREATED','WebhookSubscription',subscription.id,{url:url.origin,events:subscription.events});res.status(201).json({subscription:{...subscription.toJSON(),secretHash:undefined},secret,warning:'Copy this signing secret now.'});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/webhooks/:id/test',scope,async(req,res,next)=>{try{const subscription=await WebhookSubscription.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId,status:'ACTIVE'}});if(!subscription)return res.status(404).json({message:'Active webhook not found.'});const delivery=await WebhookDelivery.create({tenantId:req.params.tenantId,subscriptionId:subscription.id,eventType:'integration.test',payload:{id:crypto.randomUUID(),createdAt:new Date().toISOString(),branchId:req.params.branchId},status:'PENDING',nextAttemptAt:new Date()});await audit(req,'WEBHOOK_TEST_QUEUED','WebhookDelivery',delivery.id,{subscriptionId:subscription.id});res.status(202).json({delivery});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/deliveries/:id/retry',scope,async(req,res,next)=>{try{const delivery=await WebhookDelivery.findOne({where:{id:req.params.id,tenantId:req.params.tenantId}});if(!delivery)return res.status(404).json({message:'Delivery not found.'});delivery.status='PENDING';delivery.nextAttemptAt=new Date();delivery.lastError=null;await delivery.save();await audit(req,'WEBHOOK_DELIVERY_RETRIED','WebhookDelivery',delivery.id);res.json({delivery});}catch(error){next(error);}});
module.exports=router;
