const express = require('express');
const { Op } = require('sequelize');
const { AuditLog, Supplier, Branch } = require('../models');
const { Order } = require('../models/sales');
const { authenticate, requireApproved, requireBranchRoles } = require('../middleware/auth');
const { ProcurementDocument, VendorMetric, OpsTask, EmployeeRecord, WorkforceEvent, CentralTemplate, CentralDispatch, InsightAutomation } = require('../models/operations');
const router = express.Router();
router.use(authenticate, requireApproved);
function access(req,res,next){return requireBranchRoles('BRANCH_MANAGER')(req,res,(error)=>{if(error)return next(error);if(!req.branch||String(req.branch.tenantId)!==String(req.params.tenantId))return res.status(404).json({message:'Branch not found in this business.'});next();});}
const clean=(value,max=255)=>String(value||'').trim().slice(0,max)||null;
const minor=(value)=>{const raw=String(value??0);if(!/^-?\d+$/.test(raw)){const error=new Error('Amount must be an integer in minor units.');error.status=400;throw error;}return raw;};
async function audit(req,action,type,id,metadata={}){await AuditLog.create({tenantId:req.params.tenantId,branchId:req.params.branchId,actorUserId:req.userId,action,entityType:type,entityId:String(id),metadata,ipAddress:req.ip||null});}

router.get('/tenants/:tenantId/branches/:branchId/overview',access,async(req,res,next)=>{try{const branch={tenantId:req.params.tenantId,branchId:req.params.branchId};const[procurement,vendorMetrics,tasks,employees,workforce,templates,dispatches,automations,suppliers]=await Promise.all([ProcurementDocument.findAll({where:branch,order:[['createdAt','DESC']],limit:150}),VendorMetric.findAll({where:branch,order:[['qualityScore','DESC']],limit:150}),OpsTask.findAll({where:branch,order:[['dueAt','ASC']],limit:200}),EmployeeRecord.findAll({where:branch,order:[['name','ASC']]}),WorkforceEvent.findAll({where:branch,order:[['createdAt','DESC']],limit:200}),CentralTemplate.findAll({where:{tenantId:req.params.tenantId},order:[['updatedAt','DESC']]}),CentralDispatch.findAll({where:{tenantId:req.params.tenantId,[Op.or]:[{sourceBranchId:req.params.branchId},{destinationBranchId:req.params.branchId}]},order:[['dispatchedAt','DESC']]}),InsightAutomation.findAll({where:{tenantId:req.params.tenantId,[Op.or]:[{branchId:req.params.branchId},{branchId:null}]},order:[['createdAt','DESC']]}),Supplier.findAll({where:{tenantId:req.params.tenantId,status:'ACTIVE'},order:[['name','ASC']]})]);res.json({procurement,vendorMetrics,tasks,employees,workforce,templates,dispatches,automations,suppliers});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/procurement',access,async(req,res,next)=>{try{const type=String(req.body?.documentType||'REQUISITION').toUpperCase();if(!['REQUISITION','PURCHASE_ORDER','GRN','VENDOR_INVOICE','DEBIT_NOTE','PAYABLE'].includes(type))return res.status(400).json({message:'Unsupported procurement document type.'});const number=clean(req.body?.documentNumber,80);if(!number)return res.status(400).json({message:'Document number is required.'});const document=await ProcurementDocument.create({tenantId:req.params.tenantId,branchId:req.params.branchId,documentType:type,documentNumber:number,status:type==='REQUISITION'?'PENDING_APPROVAL':'DRAFT',vendorId:req.body?.vendorId||null,parentId:req.body?.parentId||null,amountMinor:minor(req.body?.amountMinor),payload:req.body?.payload||{},attachment:req.body?.attachment||null,ocrResult:req.body?.ocrResult||null,createdByUserId:req.userId});await audit(req,'PROCUREMENT_DOCUMENT_CREATED','ProcurementDocument',document.id,{documentType:type,documentNumber:number});res.status(201).json({document});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/procurement/:id/transition',access,async(req,res,next)=>{try{const document=await ProcurementDocument.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!document)return res.status(404).json({message:'Procurement document not found.'});const status=String(req.body?.status||'').toUpperCase();if(!['APPROVED','REJECTED','RECEIVED','POSTED','PAID','VOIDED'].includes(status))return res.status(400).json({message:'Unsupported transition.'});document.status=status;if(status==='APPROVED'){document.approvedByUserId=req.userId;document.approvedAt=new Date();}await document.save();await audit(req,'PROCUREMENT_STATUS_CHANGED','ProcurementDocument',document.id,{from:document.previous('status'),to:status});res.json({document});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/vendor-metrics',access,async(req,res,next)=>{try{const supplier=await Supplier.findOne({where:{id:req.body?.vendorId,tenantId:req.params.tenantId}});if(!supplier)return res.status(404).json({message:'Vendor not found.'});const metric=await VendorMetric.create({tenantId:req.params.tenantId,branchId:req.params.branchId,vendorId:supplier.id,productId:req.body?.productId||null,quotedPriceMinor:req.body?.quotedPriceMinor==null?null:minor(req.body.quotedPriceMinor),onTimeRateBps:Number(req.body?.onTimeRateBps??10000),qualityScore:Number(req.body?.qualityScore??100),leadTimeDays:Number(req.body?.leadTimeDays??0),notes:clean(req.body?.notes,2000)});await audit(req,'VENDOR_METRIC_RECORDED','VendorMetric',metric.id,{vendorId:supplier.id});res.status(201).json({metric});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/tasks',access,async(req,res,next)=>{try{const title=clean(req.body?.title,240);if(!title)return res.status(400).json({message:'Task title is required.'});const task=await OpsTask.create({tenantId:req.params.tenantId,branchId:req.params.branchId,title,description:clean(req.body?.description,3000),priority:String(req.body?.priority||'NORMAL').toUpperCase(),recurrence:clean(req.body?.recurrence,80),dueAt:req.body?.dueAt||null,assigneeUserId:req.body?.assigneeUserId||null,createdByUserId:req.userId});await audit(req,'OPS_TASK_CREATED','OpsTask',task.id,{recurrence:task.recurrence});res.status(201).json({task});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/tasks/:id/transition',access,async(req,res,next)=>{try{const task=await OpsTask.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!task)return res.status(404).json({message:'Task not found.'});const status=String(req.body?.status||'').toUpperCase();if(!['IN_PROGRESS','COMPLETED','APPROVED','REJECTED','ESCALATED'].includes(status))return res.status(400).json({message:'Unsupported task status.'});task.status=status;if(req.body?.evidence)task.evidence=req.body.evidence;if(req.body?.score!=null)task.score=Math.max(0,Math.min(100,Number(req.body.score)));if(status==='COMPLETED')task.completedAt=new Date();if(status==='APPROVED')task.approvedByUserId=req.userId;if(status==='ESCALATED')task.escalatedAt=new Date();await task.save();await audit(req,'OPS_TASK_STATUS_CHANGED','OpsTask',task.id,{status,score:task.score});res.json({task});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/employees',access,async(req,res,next)=>{try{const name=clean(req.body?.name,180),code=clean(req.body?.employeeCode,60),jobTitle=clean(req.body?.jobTitle,120);if(!name||!code||!jobTitle)return res.status(400).json({message:'Employee code, name and job title are required.'});const employee=await EmployeeRecord.create({tenantId:req.params.tenantId,branchId:req.params.branchId,employeeCode:code,name,phone:clean(req.body?.phone,40),jobTitle,payRateMinor:minor(req.body?.payRateMinor),joinedOn:req.body?.joinedOn||null,documents:req.body?.documents||[]});await audit(req,'EMPLOYEE_RECORD_CREATED','EmployeeRecord',employee.id,{employeeCode:code});res.status(201).json({employee});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/workforce-events',access,async(req,res,next)=>{try{const employee=await EmployeeRecord.findOne({where:{id:req.body?.employeeId,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!employee)return res.status(404).json({message:'Employee not found.'});const eventType=String(req.body?.eventType||'ROSTER').toUpperCase();if(!['ROSTER','ATTENDANCE','LEAVE','PAYROLL','ADVANCE'].includes(eventType))return res.status(400).json({message:'Unsupported workforce event.'});const event=await WorkforceEvent.create({tenantId:req.params.tenantId,branchId:req.params.branchId,employeeId:employee.id,eventType,startsAt:req.body?.startsAt||null,endsAt:req.body?.endsAt||null,status:['ATTENDANCE','ROSTER'].includes(eventType)?'RECORDED':'PENDING',amountMinor:minor(req.body?.amountMinor),payload:req.body?.payload||{},createdByUserId:req.userId});await audit(req,'WORKFORCE_EVENT_CREATED','WorkforceEvent',event.id,{eventType,employeeId:employee.id});res.status(201).json({event});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/workforce-events/:id/approve',access,async(req,res,next)=>{try{const event=await WorkforceEvent.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!event)return res.status(404).json({message:'Workforce event not found.'});event.status='APPROVED';event.approvedByUserId=req.userId;await event.save();await audit(req,'WORKFORCE_EVENT_APPROVED','WorkforceEvent',event.id,{eventType:event.eventType});res.json({event});}catch(error){next(error);}});
router.get('/tenants/:tenantId/branches/:branchId/workforce-export.csv',access,async(req,res,next)=>{try{const employees=await EmployeeRecord.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},order:[['employeeCode','ASC']]}),events=await WorkforceEvent.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId},order:[['createdAt','ASC']]});const escape=(value)=>`"${String(value??'').replaceAll('"','""')}"`;const rows=[['employeeCode','name','jobTitle','eventType','startsAt','endsAt','status','amountMinor'].join(',')];for(const employee of employees){const own=events.filter((row)=>String(row.employeeId)===String(employee.id));if(!own.length)rows.push([employee.employeeCode,employee.name,employee.jobTitle,'','','',employee.status,0].map(escape).join(','));for(const event of own)rows.push([employee.employeeCode,employee.name,employee.jobTitle,event.eventType,event.startsAt?.toISOString()||'',event.endsAt?.toISOString()||'',event.status,event.amountMinor].map(escape).join(','));}res.set({'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="workforce-${req.params.branchId}.csv"`});res.send(`\uFEFF${rows.join('\n')}`);}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/templates',access,async(req,res,next)=>{try{const name=clean(req.body?.name,180),templateType=String(req.body?.templateType||'MENU').toUpperCase();if(!name||!['MENU','RECIPE','PRICE'].includes(templateType))return res.status(400).json({message:'Valid template name and type are required.'});const template=await CentralTemplate.create({tenantId:req.params.tenantId,name,templateType,status:req.body?.publish?'PUBLISHED':'DRAFT',payload:req.body?.payload||{},createdByUserId:req.userId,publishedAt:req.body?.publish?new Date():null});await audit(req,'CENTRAL_TEMPLATE_CREATED','CentralTemplate',template.id,{templateType,status:template.status});res.status(201).json({template});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/dispatches',access,async(req,res,next)=>{try{const destination=await Branch.findOne({where:{id:req.body?.destinationBranchId,tenantId:req.params.tenantId,status:'ACTIVE'}});if(!destination)return res.status(404).json({message:'Destination branch not found.'});const dispatch=await CentralDispatch.create({tenantId:req.params.tenantId,sourceBranchId:req.params.branchId,destinationBranchId:destination.id,templateId:req.body?.templateId||null,payload:req.body?.payload||{},status:'DISPATCHED',dispatchedAt:new Date(),createdByUserId:req.userId});await audit(req,'CENTRAL_DISPATCH_CREATED','CentralDispatch',dispatch.id,{destinationBranchId:destination.id});res.status(201).json({dispatch});}catch(error){next(error);}});

router.post('/tenants/:tenantId/branches/:branchId/automations',access,async(req,res,next)=>{try{const name=clean(req.body?.name,180),reportType=clean(req.body?.reportType,60);if(!name||!reportType)return res.status(400).json({message:'Name and report type are required.'});const automation=await InsightAutomation.create({tenantId:req.params.tenantId,branchId:req.params.branchId,name,reportType,schedule:clean(req.body?.schedule,80),alertRules:req.body?.alertRules||{},createdByUserId:req.userId});await audit(req,'INSIGHT_AUTOMATION_CREATED','InsightAutomation',automation.id,{reportType,schedule:automation.schedule});res.status(201).json({automation});}catch(error){next(error);}});
router.post('/tenants/:tenantId/branches/:branchId/automations/:id/run',access,async(req,res,next)=>{try{const automation=await InsightAutomation.findOne({where:{id:req.params.id,tenantId:req.params.tenantId,branchId:req.params.branchId}});if(!automation)return res.status(404).json({message:'Automation not found.'});const since=new Date(Date.now()-14*86400000);const orders=await Order.findAll({where:{tenantId:req.params.tenantId,branchId:req.params.branchId,status:{[Op.in]:['PAID','REFUNDED']},createdAt:{[Op.gte]:since}},attributes:['createdAt','totalMinor']});const days=new Map();for(const row of orders){const day=row.createdAt.toISOString().slice(0,10);days.set(day,(days.get(day)||0n)+BigInt(row.totalMinor||0));}const values=[...days.values()];const average=values.length?values.reduce((a,b)=>a+b,0n)/BigInt(values.length):0n;const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);const actual=days.get(yesterday)||0n;const variance=average?Number((actual-average)*10000n/average):0;automation.lastRunAt=new Date();automation.lastResult={forecastNextDayMinor:average.toString(),yesterdayMinor:actual.toString(),varianceBps:variance,anomaly:Math.abs(variance)>=3000};await automation.save();await audit(req,'INSIGHT_AUTOMATION_RUN','InsightAutomation',automation.id,automation.lastResult);res.json({automation});}catch(error){next(error);}});
module.exports=router;
