const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Customer = sequelize.models.Customer || sequelize.define('Customer', {
  id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true},tenantId:{type:DataTypes.UUID,allowNull:false},name:{type:DataTypes.STRING(160),allowNull:true},phone:{type:DataTypes.STRING(40),allowNull:false},email:{type:DataTypes.STRING(320),allowNull:true},consentMarketing:{type:DataTypes.BOOLEAN,allowNull:false,defaultValue:false},loyaltyPoints:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},walletMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},visitCount:{type:DataTypes.INTEGER,allowNull:false,defaultValue:0},totalSpendMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},lastVisitAt:{type:DataTypes.DATE,allowNull:true}
},{tableName:'customers'});

const GuestOrderRequest = sequelize.models.GuestOrderRequest || sequelize.define('GuestOrderRequest', {
  id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true},tenantId:{type:DataTypes.UUID,allowNull:false},branchId:{type:DataTypes.UUID,allowNull:false},tableId:{type:DataTypes.UUID,allowNull:true},customerId:{type:DataTypes.UUID,allowNull:true},channel:{type:DataTypes.STRING(32),allowNull:false},fulfillment:{type:DataTypes.STRING(32),allowNull:false},guestName:{type:DataTypes.STRING(160),allowNull:true},phone:{type:DataTypes.STRING(40),allowNull:true},cart:{type:DataTypes.JSONB,allowNull:false},subtotalMinor:{type:DataTypes.BIGINT,allowNull:false},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'PENDING'},notes:{type:DataTypes.TEXT,allowNull:true},idempotencyKey:{type:DataTypes.STRING(180),allowNull:true},acceptedOrderId:{type:DataTypes.UUID,allowNull:true},acceptedByUserId:{type:DataTypes.UUID,allowNull:true},acceptedAt:{type:DataTypes.DATE,allowNull:true},rejectionReason:{type:DataTypes.TEXT,allowNull:true},paymentMethod:{type:DataTypes.STRING(24),allowNull:true},paymentReference:{type:DataTypes.STRING(180),allowNull:true},paymentStatus:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'PAY_AT_OUTLET'},paymentVerifiedByUserId:{type:DataTypes.UUID,allowNull:true},paymentVerifiedAt:{type:DataTypes.DATE,allowNull:true}
},{tableName:'guest_order_requests'});

const CustomerFeedback = sequelize.models.CustomerFeedback || sequelize.define('CustomerFeedback', {id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true},tenantId:{type:DataTypes.UUID,allowNull:false},branchId:{type:DataTypes.UUID,allowNull:false},customerId:{type:DataTypes.UUID,allowNull:true},orderId:{type:DataTypes.UUID,allowNull:true},rating:{type:DataTypes.INTEGER,allowNull:false},comment:{type:DataTypes.TEXT,allowNull:true},contactAllowed:{type:DataTypes.BOOLEAN,allowNull:false,defaultValue:false}},{tableName:'customer_feedback'});
const Offer = sequelize.models.Offer || sequelize.define('Offer',{id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true},tenantId:{type:DataTypes.UUID,allowNull:false},code:{type:DataTypes.STRING(40),allowNull:false},name:{type:DataTypes.STRING(160),allowNull:false},discountType:{type:DataTypes.STRING(24),allowNull:false},discountValue:{type:DataTypes.BIGINT,allowNull:false},minimumSpendMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},startsAt:{type:DataTypes.DATE,allowNull:true},endsAt:{type:DataTypes.DATE,allowNull:true},active:{type:DataTypes.BOOLEAN,allowNull:false,defaultValue:true}},{tableName:'offers'});
const LoyaltyTransaction = sequelize.models.LoyaltyTransaction || sequelize.define('LoyaltyTransaction',{id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true},tenantId:{type:DataTypes.UUID,allowNull:false},customerId:{type:DataTypes.UUID,allowNull:false},orderId:{type:DataTypes.UUID,allowNull:true},pointsDelta:{type:DataTypes.BIGINT,allowNull:false},walletDeltaMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},reason:{type:DataTypes.TEXT,allowNull:false},actorUserId:{type:DataTypes.UUID,allowNull:true}},{tableName:'loyalty_transactions'});

module.exports={Customer,GuestOrderRequest,CustomerFeedback,Offer,LoyaltyTransaction};
