const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const base = { id:{type:DataTypes.UUID,defaultValue:DataTypes.UUIDV4,primaryKey:true}, tenantId:{type:DataTypes.UUID,allowNull:false} };
const ProcurementDocument = sequelize.models.ProcurementDocument || sequelize.define('ProcurementDocument',{...base,branchId:{type:DataTypes.UUID,allowNull:false},documentType:{type:DataTypes.STRING(32),allowNull:false},documentNumber:{type:DataTypes.STRING(80),allowNull:false},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'DRAFT'},vendorId:{type:DataTypes.UUID,allowNull:true},parentId:{type:DataTypes.UUID,allowNull:true},amountMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},payload:{type:DataTypes.JSONB,allowNull:false,defaultValue:{}},attachment:{type:DataTypes.JSONB,allowNull:true},ocrResult:{type:DataTypes.JSONB,allowNull:true},createdByUserId:{type:DataTypes.UUID,allowNull:false},approvedByUserId:{type:DataTypes.UUID,allowNull:true},approvedAt:{type:DataTypes.DATE,allowNull:true}},{tableName:'procurement_documents'});
const VendorMetric = sequelize.models.VendorMetric || sequelize.define('VendorMetric',{...base,branchId:{type:DataTypes.UUID,allowNull:false},vendorId:{type:DataTypes.UUID,allowNull:false},productId:{type:DataTypes.UUID,allowNull:true},quotedPriceMinor:{type:DataTypes.BIGINT,allowNull:true},onTimeRateBps:{type:DataTypes.INTEGER,allowNull:false,defaultValue:10000},qualityScore:{type:DataTypes.INTEGER,allowNull:false,defaultValue:100},leadTimeDays:{type:DataTypes.INTEGER,allowNull:false,defaultValue:0},notes:{type:DataTypes.TEXT,allowNull:true}},{tableName:'vendor_metrics'});
const OpsTask = sequelize.models.OpsTask || sequelize.define('OpsTask',{...base,branchId:{type:DataTypes.UUID,allowNull:false},title:{type:DataTypes.STRING(240),allowNull:false},description:{type:DataTypes.TEXT,allowNull:true},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'OPEN'},priority:{type:DataTypes.STRING(16),allowNull:false,defaultValue:'NORMAL'},recurrence:{type:DataTypes.STRING(80),allowNull:true},dueAt:{type:DataTypes.DATE,allowNull:true},assigneeUserId:{type:DataTypes.UUID,allowNull:true},evidence:{type:DataTypes.JSONB,allowNull:true},score:{type:DataTypes.INTEGER,allowNull:true},createdByUserId:{type:DataTypes.UUID,allowNull:false},approvedByUserId:{type:DataTypes.UUID,allowNull:true},completedAt:{type:DataTypes.DATE,allowNull:true},escalatedAt:{type:DataTypes.DATE,allowNull:true}},{tableName:'ops_tasks'});
const EmployeeRecord = sequelize.models.EmployeeRecord || sequelize.define('EmployeeRecord',{...base,branchId:{type:DataTypes.UUID,allowNull:false},userId:{type:DataTypes.UUID,allowNull:true},employeeCode:{type:DataTypes.STRING(60),allowNull:false},name:{type:DataTypes.STRING(180),allowNull:false},phone:{type:DataTypes.STRING(40),allowNull:true},jobTitle:{type:DataTypes.STRING(120),allowNull:false},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'ACTIVE'},payRateMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},joinedOn:{type:DataTypes.DATEONLY,allowNull:true},documents:{type:DataTypes.JSONB,allowNull:false,defaultValue:[]}},{tableName:'employee_records'});
const WorkforceEvent = sequelize.models.WorkforceEvent || sequelize.define('WorkforceEvent',{...base,branchId:{type:DataTypes.UUID,allowNull:false},employeeId:{type:DataTypes.UUID,allowNull:false},eventType:{type:DataTypes.STRING(32),allowNull:false},startsAt:{type:DataTypes.DATE,allowNull:true},endsAt:{type:DataTypes.DATE,allowNull:true},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'PENDING'},amountMinor:{type:DataTypes.BIGINT,allowNull:false,defaultValue:0},payload:{type:DataTypes.JSONB,allowNull:false,defaultValue:{}},createdByUserId:{type:DataTypes.UUID,allowNull:false},approvedByUserId:{type:DataTypes.UUID,allowNull:true}},{tableName:'workforce_events'});
const CentralTemplate = sequelize.models.CentralTemplate || sequelize.define('CentralTemplate',{...base,name:{type:DataTypes.STRING(180),allowNull:false},templateType:{type:DataTypes.STRING(32),allowNull:false},version:{type:DataTypes.INTEGER,allowNull:false,defaultValue:1},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'DRAFT'},payload:{type:DataTypes.JSONB,allowNull:false,defaultValue:{}},createdByUserId:{type:DataTypes.UUID,allowNull:false},publishedAt:{type:DataTypes.DATE,allowNull:true}},{tableName:'central_templates'});
const CentralDispatch = sequelize.models.CentralDispatch || sequelize.define('CentralDispatch',{...base,sourceBranchId:{type:DataTypes.UUID,allowNull:false},destinationBranchId:{type:DataTypes.UUID,allowNull:false},templateId:{type:DataTypes.UUID,allowNull:true},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'DISPATCHED'},payload:{type:DataTypes.JSONB,allowNull:false,defaultValue:{}},dispatchedAt:{type:DataTypes.DATE,allowNull:false},receivedAt:{type:DataTypes.DATE,allowNull:true},createdByUserId:{type:DataTypes.UUID,allowNull:false}},{tableName:'central_dispatches'});
const InsightAutomation = sequelize.models.InsightAutomation || sequelize.define('InsightAutomation',{...base,branchId:{type:DataTypes.UUID,allowNull:true},name:{type:DataTypes.STRING(180),allowNull:false},reportType:{type:DataTypes.STRING(60),allowNull:false},schedule:{type:DataTypes.STRING(80),allowNull:true},alertRules:{type:DataTypes.JSONB,allowNull:false,defaultValue:{}},status:{type:DataTypes.STRING(24),allowNull:false,defaultValue:'ACTIVE'},lastRunAt:{type:DataTypes.DATE,allowNull:true},lastResult:{type:DataTypes.JSONB,allowNull:true},createdByUserId:{type:DataTypes.UUID,allowNull:false}},{tableName:'insight_automations'});
module.exports={ProcurementDocument,VendorMetric,OpsTask,EmployeeRecord,WorkforceEvent,CentralTemplate,CentralDispatch,InsightAutomation};
